import type { LucideProps } from 'lucide-react';
import {
  Aperture,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Award,
  BadgeCheck,
  Ban,
  BarChart3,
  BookOpen,
  Box,
  Boxes,
  Briefcase,
  Brush,
  Building2,
  Calendar,
  Camera,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Circle,
  Clock,
  Cloud,
  Code2,
  Compass,
  Component,
  Copy,
  Cpu,
  Database,
  Download,
  Dribbble,
  ExternalLink,
  FileText,
  Film,
  Flame,
  FlaskConical,
  FolderGit2,
  GitBranch,
  Github,
  Globe,
  GraduationCap,
  Grid3x3,
  GripVertical,
  Handshake,
  Headphones,
  Heart,
  Home,
  Image,
  Info,
  Instagram,
  Key,
  Languages,
  Layers,
  Layout,
  LayoutList,
  LayoutTemplate,
  Library,
  LineChart,
  Link,
  Linkedin,
  Loader2,
  Lock,
  Mail,
  MapPin,
  Megaphone,
  Menu,
  MessageSquare,
  Mic,
  Microscope,
  Milestone,
  Music,
  NotebookPen,
  Palette,
  PanelBottom,
  PanelsTopLeft,
  PenTool,
  Pencil,
  Phone,
  PieChart,
  Play,
  Plus,
  Presentation,
  Quote,
  Rocket,
  RotateCcw,
  Rss,
  Send,
  Server,
  Settings,
  Settings2,
  ShieldCheck,
  ShoppingBag,
  SlidersHorizontal,
  Sparkles,
  Square,
  Star,
  Target,
  Terminal,
  Trash2,
  TrendingUp,
  Trophy,
  Twitch,
  Twitter,
  Upload,
  User,
  UserCheck,
  Users,
  Video,
  Wand2,
  Workflow,
  Wrench,
  X,
  Youtube,
  Zap,
} from 'lucide-react';

/**
 * Registre statique : seules les icônes réellement proposées sont empaquetées,
 * ce qui évite d'embarquer l'intégralité de lucide-react dans le bundle.
 */
const REGISTRY: Record<string, React.ComponentType<LucideProps>> = {
  'aperture': Aperture,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-up-right': ArrowUpRight,
  'award': Award,
  'badge-check': BadgeCheck,
  'ban': Ban,
  'bar-chart-3': BarChart3,
  'book-open': BookOpen,
  'box': Box,
  'boxes': Boxes,
  'briefcase': Briefcase,
  'brush': Brush,
  'building-2': Building2,
  'calendar': Calendar,
  'camera': Camera,
  'check': Check,
  'check-circle-2': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'circle': Circle,
  'clock': Clock,
  'cloud': Cloud,
  'code-2': Code2,
  'compass': Compass,
  'component': Component,
  'copy': Copy,
  'cpu': Cpu,
  'database': Database,
  'download': Download,
  'dribbble': Dribbble,
  'external-link': ExternalLink,
  'file-text': FileText,
  'film': Film,
  'flame': Flame,
  'flask-conical': FlaskConical,
  'folder-git-2': FolderGit2,
  'git-branch': GitBranch,
  'github': Github,
  'globe': Globe,
  'graduation-cap': GraduationCap,
  'grid-3x3': Grid3x3,
  'grip-vertical': GripVertical,
  'handshake': Handshake,
  'headphones': Headphones,
  'heart': Heart,
  'home': Home,
  'image': Image,
  'info': Info,
  'instagram': Instagram,
  'key': Key,
  'languages': Languages,
  'layers': Layers,
  'layout': Layout,
  'layout-list': LayoutList,
  'layout-template': LayoutTemplate,
  'library': Library,
  'line-chart': LineChart,
  'link': Link,
  'linkedin': Linkedin,
  'loader-2': Loader2,
  'lock': Lock,
  'mail': Mail,
  'map-pin': MapPin,
  'megaphone': Megaphone,
  'menu': Menu,
  'message-square': MessageSquare,
  'mic': Mic,
  'microscope': Microscope,
  'milestone': Milestone,
  'music': Music,
  'notebook-pen': NotebookPen,
  'palette': Palette,
  'panel-bottom': PanelBottom,
  'panels-top-left': PanelsTopLeft,
  'pen-tool': PenTool,
  'pencil': Pencil,
  'phone': Phone,
  'pie-chart': PieChart,
  'play': Play,
  'plus': Plus,
  'presentation': Presentation,
  'quote': Quote,
  'rocket': Rocket,
  'rotate-ccw': RotateCcw,
  'rss': Rss,
  'send': Send,
  'server': Server,
  'settings': Settings,
  'settings-2': Settings2,
  'shield-check': ShieldCheck,
  'shopping-bag': ShoppingBag,
  'sliders-horizontal': SlidersHorizontal,
  'sparkles': Sparkles,
  'square': Square,
  'star': Star,
  'target': Target,
  'terminal': Terminal,
  'trash-2': Trash2,
  'trending-up': TrendingUp,
  'trophy': Trophy,
  'twitch': Twitch,
  'twitter': Twitter,
  'upload': Upload,
  'user': User,
  'user-check': UserCheck,
  'users': Users,
  'video': Video,
  'wand-2': Wand2,
  'workflow': Workflow,
  'wrench': Wrench,
  'x': X,
  'youtube': Youtube,
  'zap': Zap,
};

/** "arrow-up-right" | "arrowUpRight" | "ArrowUpRight" -> clé normalisée */
function normalize(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .toLowerCase()
    .replace(/^-+|-+$/g, '');
}

interface IconProps extends Omit<LucideProps, 'ref'> {
  name: string;
  /** icône de repli si le nom est inconnu */
  fallback?: string;
}

export default function Icon({ name, fallback = 'circle', ...props }: IconProps) {
  if (!name) return null;
  const Cmp = REGISTRY[normalize(name)] ?? REGISTRY[normalize(fallback)];
  if (!Cmp) return null;
  return <Cmp strokeWidth={2} {...props} />;
}

export const ICON_LIBRARY: string[] = [
  'sparkles', 'zap', 'star', 'heart', 'flame', 'award', 'badge-check', 'trophy',
  'code-2', 'terminal', 'server', 'database', 'cloud', 'cpu', 'git-branch', 'github',
  'layout', 'layout-template', 'layers', 'component', 'boxes', 'box', 'grid-3x3', 'panels-top-left',
  'palette', 'brush', 'pen-tool', 'image', 'camera', 'film', 'aperture', 'wand-2',
  'briefcase', 'target', 'compass', 'workflow', 'trending-up', 'bar-chart-3', 'pie-chart', 'line-chart',
  'graduation-cap', 'book-open', 'library', 'microscope', 'flask-conical', 'file-text', 'notebook-pen', 'languages',
  'users', 'user', 'user-check', 'handshake', 'message-square', 'quote', 'megaphone', 'presentation',
  'mail', 'send', 'phone', 'map-pin', 'globe', 'link', 'external-link', 'calendar',
  'clock', 'shield-check', 'lock', 'key', 'settings', 'sliders-horizontal', 'wrench', 'rocket',
  'linkedin', 'instagram', 'twitter', 'youtube', 'dribbble', 'twitch', 'rss', 'download',
  'arrow-right', 'arrow-up-right', 'arrow-up', 'chevron-right', 'plus', 'check', 'x', 'milestone',
  'music', 'mic', 'headphones', 'video', 'play', 'shopping-bag', 'building-2', 'home',
];
